### ISSUE TITLE
Doesn't work with ASCII escapes (i.e. colors)

### ISSUE THREAD

**Issue by juniorRubyist** [astanin/python-tabulate#8] opened 2019-09-29 15:31 UTC
When I use tabulate with color sequences, all of the data doesn't line up with the headers.
Here are examples:

Colorized
```
Assignment                                                                             %        Points      Max Pts.  Comment                        Category
-------------------------------------------------------------------------------------  -------  --------  ----------  -----------------------------  --------------------------------------------------------------------------------
L7 Quiz, L7 PY, translation, questions, P46 to P49 ALL SECTIONS                   E        -                200                                 Quizzes for Chinese classes / Keyboarding and Weekly Planner check for CCP class
P36 & L6 Pinyin, Translation & Qs, P38 to P43 ALL SECTIONS!                       E        -                200                                 Quizzes for Chinese classes / Keyboarding and Weekly Planner check for CCP class
```

Uncolorized
```
Assignment                                                                        %        Points      Max Pts.  Comment                        Category
--------------------------------------------------------------------------------  -------  --------  ----------  -----------------------------  --------------------------------------------------------------------------------
L7 Quiz, L7 PY, translation, questions, P46 to P49 ALL SECTIONS                   E        -                200                                 Quizzes for Chinese classes / Keyboarding and Weekly Planner check for CCP class
P36 & L6 Pinyin, Translation & Qs, P38 to P43 ALL SECTIONS!                       E        -                200                                 Quizzes for Chinese classes / Keyboarding and Weekly Planner check for CCP class
```

**Comment by astanin** [comment] 2019-09-30 08:06
Could you please post the code with color sequences that break alignment?

What Python version and library version do you use? (tabulate.__version__)

In tabulate 0.8.5 regular expressions which detect and filter escape sequences were slightly modified to make them compatible with Python 3.7 and later versions. This change didn't break any test, but who knows.

**Comment by juniorRubyist** [comment] 2019-09-30 21:30
I am using tabulate 0.8.5 with Python 3.7.1. I generated the color sequences using colorama 0.4.1.

**Comment by astanin** [comment] 2019-10-01 07:39
I tried to reproduce the bug, but it works for me:

```
>>> tbl = [[colorama.Fore.RED + "red" + colorama.Style.RESET_ALL, 1], ["abc", 2]]
>>> print(tabulate.tabulate(tbl))
---  -
red  1
abc  2
---  -
>>> tbl2 = [[colorama.Back.YELLOW + "yellow" + colorama.Back.RESET + " submarine", "colorized"],
... ["yellow submarine", "normal"]]
>>> print(tabulate.tabulate(tbl2))
----------------  ---------
yellow submarine  colorized
yellow submarine  normal
----------------  ---------
```

Ubuntu 18.04, colorama 0.3.7, tabulate from the git master (pretty much the same as 0.8.5).

Are you using Windows? Please note that on Windows colorama works differently:

> On Windows, calling init() will filter ANSI escape sequences out of any text sent to stdout or stderr, and replace them with equivalent Win32 calls.

I will need to know what strings exactly get their length printed incorrectly to be able to fix this.

Tabulate works by eliminating invisible codes and ANSI escape sequences before calculating column width. What is recognized as codes to be removed is defined by these regular expressions:

https://github.com/astanin/python-tabulate/blob/d54eaf6/tabulate.py#L503-L508

**Comment by chugcup** [comment] 2019-10-31 22:56
Just to chime in, I had a similar issue with colorized ANSI text and column widths and I found that the issue was my generated text was not regex matching the closing (reset) control sequence because I omitted the `0` [reset all](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters) code.

So while the sequence
`'\x1b[1;31mred\x1b[m'`
technically prints "red" as intended, the proper reset sequence should be
`'\x1b[1;31mred\x1b[0m'`
which matches the regex compiled pattern in this library.

**Comment by astanin** [comment] 2020-01-15 11:28
I close this issue as it didn't receive further feedback, and cannot be reproduced.

**Closed by astanin** 2020-01-15 11:28 UTC
Labels: invalid, question
