### ISSUE TITLE
tabulate version 0.8.4 installation on Windows results in UnicodeDecodeError

### ISSUE THREAD

**Issue by wchill** [astanin/python-tabulate#4] opened 2019-09-25 01:09 UTC
Hi, my team is seeing issues installing version 0.8.4 (it's a dependency of one of the other pypi packages we use).

`UnicodeEncodeError: 'charmap' codec can't encode characters in position 5907-5924: character maps to <undefined>`

```
(env) PS C:\Users\wchill\Projects> pip install tabulate
Collecting tabulate
  Downloading https://files.pythonhosted.org/packages/76/35/ae65ed1268d6e2a1be141723e5fffdf4a28e4f4e7c1e083709b308998f90/tabulate-0.8.4.tar.gz (45kB)
     |████████████████████████████████| 51kB 1.1MB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\wchill\projects\env\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\WCHILL\\AppData\\Local\\Temp\\pip-install-u6zf4jij\\tabulate\\setup.py'"'"'; __file__='"'"'C:\\Users\\WCHILL\\AppData\\Local\\Temp\\pip-install-u6zf4jij\\tabulate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\WCHILL\AppData\Local\Temp\pip-install-u6zf4jij\tabulate\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\WCHILL\AppData\Local\Temp\pip-install-u6zf4jij\tabulate\setup.py", line 25, in <module>
        f.write(LONG_DESCRIPTION)
      File "c:\users\wchill\projects\env\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode characters in position 5907-5924: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by neerajanil** [comment] 2019-09-25 02:42
Facing the same issue on 0.8.4 ; 0.8.3 is installing without any issues.

**Comment by greenu** [comment] 2019-09-25 10:31
I have same issue with python 3 on Centos 7. To reproduce:
```
docker run -it centos:7
yum install python3
pip3 install tabulate==0.8.4
```

```
Collecting tabulate==0.8.4
  Using cached https://files.pythonhosted.org/packages/76/35/ae65ed1268d6e2a1be141723e5fffdf4a28e4f4e7c1e083709b308998f90/tabulate-0.8.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-p8p1mdf_/tabulate/setup.py", line 25, in <module>
        f.write(LONG_DESCRIPTION)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 5711-5728: ordinal not in range(128)
```

**Comment by michaelkaye** [comment] 2019-09-25 12:01
I believe the problem is that the conversion to markdown of the README.md file now contains characters outside of the 'ascii' codec: `══` in the tables.

**Comment by asvetlov** [comment] 2019-09-25 15:09
Have the same issue.
I very appreciate if you release a bugfix soon, the fix is really trivial.

**Comment by imatiach-msft** [comment] 2019-09-25 15:26
have same issue.
the issue is already fixed with this commit it seems:
https://github.com/astanin/python-tabulate/commit/dbf6b6d78bd681d6d1f3ef8ed5e233c06f6246cf

author @astanin  just needs to publish 0.8.5 version

the problem is the readme contains utf-8 characters but the long_description field in setup.py can only handle ascii

**Comment by astanin** [comment] 2019-09-25 15:48
The problem was a debug print (f.write) left in the setup script.

It should be fixed in 0.8.5, which I have just uploaded to PyPI. Installs on Windows and Linux for me.

Sorry for inconvenience.

**Closed** 2019-09-25 15:48 UTC

**Comment by michaelkaye** [comment] 2019-09-25 15:51
Looks good from my tests too. Thanks for being so responsive!

**Comment by imatiach-msft** [comment] 2019-09-25 15:53
great, new version works for me as well, thank you!
