### ISSUE TITLE
Output garbled after 1000 lines

### ISSUE THREAD

**Issue by thorstenkampe** [astanin/python-tabulate#102] opened 2020-12-10 21:51 UTC
Certain table formats print garbled output in JupyterLab after more than 1000 entries.

There are problems with the following formats:  github, grid, psql, fancy_grid and pretty. Pretty's limit is even lower: 145.

It happens only with `headers='keys'`.

Code to demonstrate the issue:
```python
import plotly as px, tabulate
data = px.data.gapminder()

print(tabulate.tabulate(data.iloc[:145], headers='keys', tablefmt='pretty'))
````

### proper output (pretty)
![image](https://user-images.githubusercontent.com/475462/101832878-790c7900-3b38-11eb-9ad9-15784345cde3.png)

### improper output (pretty)
![image](https://user-images.githubusercontent.com/475462/101833058-b6710680-3b38-11eb-9216-9dd540d401d2.png)

### improper output (github)
![image](https://user-images.githubusercontent.com/475462/101833220-eddfb300-3b38-11eb-842f-59dc35e0991c.png)

### improper output (grid)
![image](https://user-images.githubusercontent.com/475462/101833376-2a131380-3b39-11eb-928b-06f11414bfce.png)

### improper output (psql)
![image](https://user-images.githubusercontent.com/475462/101833486-5cbd0c00-3b39-11eb-8be5-cc66d8ea6f19.png)

### improper output (fancy_grid)
![image](https://user-images.githubusercontent.com/475462/101833588-7e1df800-3b39-11eb-9fd2-ac8a0a48baa1.png)

**Comment by astanin** [comment] 2021-02-18 00:54
Sorry, I don't see what's wrong with fancy_grid (improper output).

Could you please highlight what exactly is wrong?

**Comment by thorstenkampe** [comment] 2021-02-20 10:54
Sorry for the delay in responding.

The header of the tables were garbled (see screenshot) and there were empty lines between the lines of the table data (and the header):
![image](https://user-images.githubusercontent.com/475462/108593116-276f3e80-7372-11eb-8aee-37e57a264fd2.png)

Anyhow, I cannot reproduce the issue anymore. I would assume an update of the modules involved fixed the issue.

**Comment by astanin** [comment] 2021-02-20 12:57
Could it be related to the width of the output window? It looks like the long lines were wrapped.

I'm glad the issue is resolved. I close the issue for now. Feel free to reopen if this problem reappears.

**Closed by astanin** 2021-02-20 12:57 UTC
Labels: question
