### ISSUE TITLE
What is the expected behaviour of unsafehtml ?

### ISSUE THREAD

**Issue by ajinabraham** [astanin/python-tabulate#103] opened 2020-12-14 00:42 UTC
```
(Pdb) fstore
[['File', 'tests/assets/node_source/true_positives/header_cors_star.js'], ['Match Position', '1 - 25'], ['Line Number(s)', 6], ['Match String', "app.options('*', cors())"]]
(Pdb) tabulate(fstore, tablefmt='html')
'<table>\n<tbody>\n<tr><td>File          </td><td>tests/assets/node_source/true_positives/header_cors_star.js</td></tr>\n<tr><td>Match Position</td><td>1 - 25                                                     </td></tr>\n<tr><td>Line Number(s)</td><td>6                                                          </td></tr>\n<tr><td>Match String  </td><td>app.options(&#x27;*&#x27;, cors())                                   </td></tr>\n</tbody>\n</table>'
(Pdb) tabulate(fstore, tablefmt='unsafehtml')
"--------------  -----------------------------------------------------------\nFile            tests/assets/node_source/true_positives/header_cors_star.js\nMatch Position  1 - 25\nLine Number(s)  6\nMatch String    app.options('*', cors())\n--------------  -----------------------------------------------------------"
```

I was expecting `unsafehtml` to output html table without html escapes.

**Comment by rpolve** [comment] 2021-01-03 10:35
This is a duplicate of #63.

**Comment by astanin** [comment] 2021-02-18 00:57
0.8.8 output:

```
>>> fstore = [['File', 'tests/assets/node_source/true_positives/header_cors_star.js'], ['Match Position', '1 - 25'], ['Line Number(s)', 6], ['Match String', "app.options('*', cors())"]]
>>> uh = tabulate(fstore, tablefmt="unsafehtml")
>>> print(uh)
<table>
<tbody>
<tr><td>File          </td><td>tests/assets/node_source/true_positives/header_cors_star.js</td></tr>
<tr><td>Match Position</td><td>1 - 25                                                     </td></tr>
<tr><td>Line Number(s)</td><td>6                                                          </td></tr>
<tr><td>Match String  </td><td>app.options('*', cors())                                   </td></tr>
</tbody>
</table>
```

**Closed by astanin** 2021-02-18 00:57 UTC
