### ISSUE TITLE
0.8.8 - ValueError: could not convert string to float.

### ISSUE THREAD

**Issue by akiva0003** [astanin/python-tabulate#114] opened 2021-02-20 22:10 UTC
```
import tabulate

print("Version:", tabulate.__version__)
table = [['A', '12,727,929'], ['B', '12,648,259'], ['C', '79,670']]
print(tabulate.tabulate(table))
```
Test 1:
```
Version: 0.8.7
-  ----------
A  12,727,929
B  12,648,259
C  79,670
-  ----------
```
Test 2:
```
Version: 0.8.8
Traceback (most recent call last):
  File "C:\Users\me\Desktop\test.py", line 5, in <module>
    print(tabulate.tabulate(table))
  File "C:\Users\me\AppData\Local\Programs\Python\Python38\lib\site-packages\tabulate.py", line 1599, in tabulate
    cols = [
  File "C:\Users\me\AppData\Local\Programs\Python\Python38\lib\site-packages\tabulate.py", line 1600, in <listcomp>
    [_format(v, ct, fl_fmt, miss_v, has_invisible) for v in c]
  File "C:\Users\me\AppData\Local\Programs\Python\Python38\lib\site-packages\tabulate.py", line 1600, in <listcomp>
    [_format(v, ct, fl_fmt, miss_v, has_invisible) for v in c]
  File "C:\Users\me\AppData\Local\Programs\Python\Python38\lib\site-packages\tabulate.py", line 1004, in _format
    return format(float(val), floatfmt)
ValueError: could not convert string to float: '12,727,929'
```

**Comment by brandonwardlaw** [comment] 2021-02-21 23:19
The issue appears to be the commas; the test above is fine if they're removed. Also replicated this behavior w/ 0.8.8.

**Comment by astanin** [comment] 2021-02-22 07:47
This bug is due to a feature introduced in 0.8.8 (pull request #51).
A regression test was added, and the feature was disabled in 0.8.9 (pull request #111).
It will be implemented differently.

This issue is duplicate of #110.

**Closed by astanin** 2021-02-22 07:47 UTC
Labels: duplicate
