### ISSUE TITLE
Option to wrap text

### ISSUE THREAD

**Issue by AtomicNess123** [astanin/python-tabulate#134] opened 2021-07-22 15:02 UTC
Hi! Is it possible to wrap the text in cells of the table when the text is too long? Thanks.

**Comment by bmayfi3ld** [comment] 2021-07-22 21:59
This looks to be a duplicate of https://github.com/astanin/python-tabulate/issues/90

**Comment by AtomicNess123** [comment] 2021-07-23 06:37
Yes, thanks. However, that piece of code did not work.

**Comment by bmayfi3ld** [comment] 2021-07-23 13:27
It has not been released yet, see https://github.com/astanin/python-tabulate/issues/131

**Closed** 2021-07-23 13:39 UTC
